services:
  awg-easy:
    build:
      context: .
      args:
        AWG_GO_COMMIT: 1b86b2ae0e493e7ea93f8c1a0f0cb6735b1551f1
        AWG_TOOLS_COMMIT: ee0f0a9aa34ff0a0da4b3433b9512781cfe02843
    image: awg-easy-3:0.1.0-dev
    container_name: awg-easy-3
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./data:/data
    read_only: true
    tmpfs:
      - /run:mode=0700,size=16m
      - /tmp:mode=1777,size=32m
    security_opt:
      - no-new-privileges:true
    environment:
      AWG_HOST: ${AWG_HOST:-}
    stop_grace_period: 15s
